// Regenerate src/api/schema.ts from the backend's OpenAPI schema (needs uv).
//   npm run api-types            write the file
//   npm run api-types -- --check fail if the file is out of date
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import process from "node:process";

import openapiTS, { astToString } from "openapi-typescript";

const OUT = "src/api/schema.ts";
const HEADER = "// Generated by `npm run api-types` from the backend's OpenAPI schema. Do not edit.\n\n";

const schema = JSON.parse(
	execFileSync("uv", ["run", "--project", "../backend", "--quiet", "python", "-m", "syncryption_server", "openapi"], {
		encoding: "utf8",
	}),
);
const output = HEADER + astToString(await openapiTS(schema, { alphabetize: true }));

if (process.argv.includes("--check")) {
	if (readFileSync(OUT, "utf8") !== output) {
		console.error(`${OUT} is out of date: run npm run api-types`);
		process.exit(1);
	}
} else {
	writeFileSync(OUT, output);
}
