// Generated by `npm run api-types` from the backend's OpenAPI schema. Do not edit.

export interface paths {
    "/api/v1/auth/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Challenge */
        post: operations["challenge_api_v1_auth_challenge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_api_v1_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Device */
        delete: operations["revoke_device_api_v1_devices__device_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Device */
        post: operations["approve_device_api_v1_devices__device_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Self Device */
        get: operations["self_device_api_v1_devices_self_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vaults */
        get: operations["list_vaults_api_v1_vaults_get"];
        put?: never;
        /** Create Vault */
        post: operations["create_vault_api_v1_vaults_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/blobs/{blob_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Blob */
        get: operations["get_blob_api_v1_vaults__vault_id__blobs__blob_id__get"];
        /** Put Blob */
        put: operations["put_blob_api_v1_vaults__vault_id__blobs__blob_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        /** Head Blob */
        head: operations["head_blob_api_v1_vaults__vault_id__blobs__blob_id__head"];
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/blobs/missing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Missing Blobs */
        post: operations["missing_blobs_api_v1_vaults__vault_id__blobs_missing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Changes */
        get: operations["changes_api_v1_vaults__vault_id__changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Head Revision */
        get: operations["head_revision_api_v1_vaults__vault_id__files__file_id__get"];
        /** Commit */
        put: operations["commit_api_v1_vaults__vault_id__files__file_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/files/{file_id}/revs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_v1_vaults__vault_id__files__file_id__revs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/files/{file_id}/revs/{rev}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Revision */
        get: operations["get_revision_api_v1_vaults__vault_id__files__file_id__revs__rev__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/keyring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Keyring */
        get: operations["get_keyring_api_v1_vaults__vault_id__keyring_get"];
        /** Put Keyring */
        put: operations["put_keyring_api_v1_vaults__vault_id__keyring_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/locks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locks */
        get: operations["list_locks_api_v1_vaults__vault_id__locks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/locks/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acquire */
        post: operations["acquire_api_v1_vaults__vault_id__locks__file_id__post"];
        /** Release */
        delete: operations["release_api_v1_vaults__vault_id__locks__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_v1_vaults__vault_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/members/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_v1_vaults__vault_id__members__device_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/members/{device_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Member */
        post: operations["approve_member_api_v1_vaults__vault_id__members__device_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recover
         * @description Upload the next keyring signed by the recovery key, and become an active member.
         */
        post: operations["recover_api_v1_vaults__vault_id__recover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recovery Keyring
         * @description The current keyring, for a device that recovers the vault (crypto.md 9).
         */
        get: operations["get_recovery_keyring_api_v1_vaults__vault_id__recovery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/wait": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wait */
        get: operations["wait_api_v1_vaults__vault_id__wait_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Vault */
        post: operations["open_vault_api_v1_vaults_open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcquireRequest */
        AcquireRequest: {
            /** Clientid */
            clientId: string;
            /**
             * Ttl
             * @default 120
             */
            ttl: number;
        };
        /** BlobInfo */
        BlobInfo: {
            /** Id */
            id: string;
            /** Size */
            size: number;
        };
        /** ChallengeRequest */
        ChallengeRequest: {
            /** Publickey */
            publicKey: string;
            /** Username */
            username: string;
        };
        /** ChallengeResponse */
        ChallengeResponse: {
            /** Challengeid */
            challengeId: string;
            /** Expiresat */
            expiresAt: string;
            /** Message */
            message: string;
        };
        /** Changes */
        Changes: {
            /** Changes */
            changes: components["schemas"]["Revision"][];
            /** Cursor */
            cursor: number;
            /** Keyringversion */
            keyringVersion: number;
            /** More */
            more: boolean;
        };
        /** CommitRequest */
        CommitRequest: {
            /** Blobs */
            blobs?: string[];
            /**
             * Deleted
             * @default false
             */
            deleted: boolean;
            /** Meta */
            meta: string;
            /** Parentrev */
            parentRev: number | null;
        };
        /** CreateRequest */
        CreateRequest: {
            /** Id */
            id: string;
            keyring: components["schemas"]["KeyringUpload"];
            /** Name */
            name: string;
        };
        /** Device */
        Device: {
            /** Createdat */
            createdAt: string;
            /** Fingerprint */
            fingerprint: string;
            /** Id */
            id: string;
            /** Lastseenat */
            lastSeenAt: string | null;
            /** Name */
            name: string;
            /** Pairingcode */
            pairingCode: string;
            /** Publickey */
            publicKey: string;
            /** Status */
            status: string;
        };
        /** DeviceList */
        DeviceList: {
            /** Devices */
            devices: components["schemas"]["Device"][];
        };
        /** History */
        History: {
            /** More */
            more: boolean;
            /** Revisions */
            revisions: components["schemas"]["Revision"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Keyring */
        Keyring: {
            /** Byrecovery */
            byRecovery: boolean;
            /** Createdat */
            createdAt: string;
            /** Keyring */
            keyring: string;
            /** Recoverysigner */
            recoverySigner?: string | null;
            /** Signature */
            signature: string;
            /** Signer */
            signer: string;
            /** Version */
            version: number;
        };
        /** KeyringUpload */
        KeyringUpload: {
            /** Keyring */
            keyring: string;
            /** Recoverysigner */
            recoverySigner?: string | null;
            /** Signature */
            signature: string;
            /** Signer */
            signer: string;
            /** Version */
            version: number;
        };
        /** Lock */
        Lock: {
            /** Clientid */
            clientId: string;
            /** Device */
            device: string;
            /** Devicename */
            deviceName: string;
            /** Expiresat */
            expiresAt: string;
            /** Fileid */
            fileId: string;
        };
        /** Locks */
        Locks: {
            /** Locks */
            locks: components["schemas"]["Lock"][];
            /** Locksseq */
            locksSeq: number;
        };
        /** Member */
        Member: {
            /** Createdat */
            createdAt: string;
            device: components["schemas"]["Device"];
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "pending";
        };
        /** MemberList */
        MemberList: {
            /** Members */
            members: components["schemas"]["Member"][];
        };
        /** MissingRequest */
        MissingRequest: {
            /** Ids */
            ids: string[];
        };
        /** MissingResponse */
        MissingResponse: {
            /** Missing */
            missing: string[];
        };
        /** OpenRequest */
        OpenRequest: {
            /** Name */
            name: string;
        };
        /** OpenResponse */
        OpenResponse: {
            /**
             * Membership
             * @enum {string}
             */
            membership: "active" | "pending";
            vault: components["schemas"]["Vault"];
        };
        /** Revision */
        Revision: {
            /** Blobs */
            blobs: string[];
            /** Createdat */
            createdAt: string;
            /** Deleted */
            deleted: boolean;
            /** Device */
            device: string;
            /** Fileid */
            fileId: string;
            /** Meta */
            meta: string;
            /** Parentrev */
            parentRev: number | null;
            /** Rev */
            rev: number;
            /** Size */
            size: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vault */
        Vault: {
            /** Createdat */
            createdAt: string;
            /** Id */
            id: string;
            /** Keyringversion */
            keyringVersion: number;
            /** Name */
            name: string;
            /** Seq */
            seq: number;
        };
        /** VaultEntry */
        VaultEntry: {
            /** Membership */
            membership: ("active" | "pending") | null;
            vault: components["schemas"]["Vault"];
        };
        /** VaultList */
        VaultList: {
            /** Vaults */
            vaults: components["schemas"]["VaultEntry"][];
        };
        /** VerifyRequest */
        VerifyRequest: {
            /** Challengeid */
            challengeId: string;
            /**
             * Devicename
             * @default Device
             */
            deviceName: string;
            /** Sharedsecret */
            sharedSecret?: string | null;
            /** Signature */
            signature: string;
        };
        /** VerifyResponse */
        VerifyResponse: {
            /** Created */
            created: boolean;
            /** Deviceid */
            deviceId: string;
            /** Expiresat */
            expiresAt: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "pending";
            /** Token */
            token: string;
        };
        /** WaitResponse */
        WaitResponse: {
            /** Changed */
            changed: boolean;
            /** Keyringversion */
            keyringVersion: number;
            /** Locksseq */
            locksSeq: number;
            /** Seq */
            seq: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    challenge_api_v1_auth_challenge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_v1_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceList"];
                };
            };
        };
    };
    revoke_device_api_v1_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_device_api_v1_devices__device_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    self_device_api_v1_devices_self_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
        };
    };
    list_vaults_api_v1_vaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VaultList"];
                };
            };
        };
    };
    create_vault_api_v1_vaults_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vault"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blob_api_v1_vaults__vault_id__blobs__blob_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blob_id: string;
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_blob_api_v1_vaults__vault_id__blobs__blob_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blob_id: string;
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlobInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    head_blob_api_v1_vaults__vault_id__blobs__blob_id__head: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blob_id: string;
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    missing_blobs_api_v1_vaults__vault_id__blobs_missing_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    changes_api_v1_vaults__vault_id__changes_get: {
        parameters: {
            query?: {
                limit?: number;
                since?: number;
            };
            header?: never;
            path: {
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Changes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    head_revision_api_v1_vaults__vault_id__files__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_api_v1_vaults__vault_id__files__file_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_v1_vaults__vault_id__files__file_id__revs_get: {
        parameters: {
            query?: {
                before?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                file_id: string;
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["History"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_revision_api_v1_vaults__vault_id__files__file_id__revs__rev__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
                rev: number;
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_keyring_api_v1_vaults__vault_id__keyring_get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Keyring"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_keyring_api_v1_vaults__vault_id__keyring_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyringUpload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Keyring"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_locks_api_v1_vaults__vault_id__locks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Locks"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acquire_api_v1_vaults__vault_id__locks__file_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcquireRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lock"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_api_v1_vaults__vault_id__locks__file_id__delete: {
        parameters: {
            query: {
                clientId: string;
            };
            header?: never;
            path: {
                file_id: string;
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_v1_vaults__vault_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v1_vaults__vault_id__members__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_member_api_v1_vaults__vault_id__members__device_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recover_api_v1_vaults__vault_id__recover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyringUpload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Keyring"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recovery_keyring_api_v1_vaults__vault_id__recovery_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Keyring"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wait_api_v1_vaults__vault_id__wait_get: {
        parameters: {
            query?: {
                keyringSince?: number | null;
                locksSince?: number;
                since?: number;
                timeout?: number;
            };
            header?: never;
            path: {
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_vault_api_v1_vaults_open_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
